sampler_partial:
  _target_: mattergen.diffusion.sampling.classifier_free_guidance.GuidedPredictorCorrector.from_pl_module
  N: 1000
  eps_t: ${eval:'1/${.N}'}

  _partial_: true
  guidance_scale: 0.0
  remove_conditioning_fn:
    _target_: mattergen.property_embeddings.SetUnconditionalEmbeddingType
  keep_conditioning_fn:
    _target_: mattergen.property_embeddings.SetConditionalEmbeddingType
  predictor_partials:
    pos:
      _target_: mattergen.diffusion.wrapped.wrapped_predictors_correctors.WrappedAncestralSamplingPredictor
      _partial_: true

  corrector_partials:
    pos:
      _target_: xtalpaint.time_dependent.corrector.TDWrappedLangevinCorrector
      _partial_: true
      max_step_size: 1e6
      snr: 0.4

  n_steps_corrector: 1

condition_loader_partial:
  _partial_: true
  _target_: mattergen.common.data.condition_factory.get_number_of_atoms_condition_loader
