_target_: mattergen.diffusion.corruption.multi_corruption.MultiCorruption
sdes:
  pos:
    _target_: mattergen.common.diffusion.corruption.NumAtomsVarianceAdjustedWrappedVESDE
    wrapping_boundary: 1.0
    sigma_max: 5.0
    limit_info_key: num_atoms
