hydra:
  run:
    dir: ${oc.env:OUTPUT_DIR,outputs/singlerun/${now:%Y-%m-%d}/${now:%H-%M-%S}}

auto_resume: False

defaults:
  - data_module: alex_mp_20
  - trainer: default
  - lightning_module: default
  - lightning_module/diffusion_module: TD-paint
  - lightning_module/diffusion_module/model: mattergen
  - lightning_module/diffusion_module/corruption: TD-paint

lightning_module:
  diffusion_module:
    _target_: xtalpaint.time_dependent.diffusion_module.TDDiffusionModule
    p_replace: 0.2
    t_replace: 0.001
    model:
      denoise_atom_types: false
